ALTER TABLE cvs DROP COLUMN IF EXISTS full_name;
ALTER TABLE cvs DROP COLUMN IF EXISTS phone_number;
ALTER TABLE cvs DROP COLUMN IF EXISTS email;
ALTER TABLE cvs DROP COLUMN IF EXISTS salary;
ALTER TABLE cvs DROP COLUMN IF EXISTS date_receipt_cv;
ALTER TABLE cvs DROP COLUMN IF EXISTS interview_method;
ALTER TABLE cvs DROP COLUMN IF EXISTS contact_link;
