package configs

var EnAssetCategories = map[string]string{
	"Asset type code":                          "Asset type code",
	"Asset code":                               "Asset code",
	"Asset name":                               "Asset name",
	"Employee Id":                              "Employee Id",
	"User name":                                "User name",
	"Managed by Id":                            "Managed by Id",
	"Managed by name":                          "Managed by name",
	"Branch":                                   "Branch",
	"Branch Id":                                "Branch Id",
	"Status":                                   "Status",
	"Description":                              "Description",
	"Purchase price":                           "Purchase price",
	"Purchase date":                            "Purchase date",
	"Warranty expiry date":                     "Warranty expiry date",
	"Used since":                               "Used since",
	"Depreciation end date":                    "Depreciation end date",
	"Depreciation period":                      "Depreciation period",
	"Row %s: asset type can't not be blank":    "Row %s: asset type can't not be blank",
	"Row %s: asset type should be number":      "Row %s: asset type should be number",
	"Row %s: asset type code not exists":       "Row %s: asset type code not exists",
	"Row %s: asset code can't not be blank":    "Row %s: asset code can't not be blank",
	"Row %s: employee id is not exist":         "Row %s: employee id is not exist",
	"Row %s: Managed by Id can't not be blank": "Row %s: Managed by Id can't not be blank",
	"Row %s: Manager employee id is not exist": "Row %s: Manager employee id is not exist",
	"Row %s: Branch Id can't not be blank":     "Row %s: Branch Id can't not be blank",
	"Row %s: Branch Id should be number":       "Row %s: Branch Id should be number",
	"Row %s: Branch Id not exists":             "Row %s: Branch Id not exists",
	"Row %s: Status can't not be blank":        "Row %s: Status can't not be blank",
	"Row %s: Status Id should be number":       "Row %s: Status Id should be number",
	"Row %s: Status Id not exists":             "Row %s: Status Id not exists",
	"Row %s: Purchase price should be number":  "Row %s: Purchase price should be number",
	"Row %s: Purchase date is invalid, it 's should be like 2006-01-02":        "Row %s: Purchase date is invalid, it 's should be like 2006-01-02",
	"Row %s: Warranty expiry date is invalid, it 's should be like 2006-01-02": "Row %s: Warranty expiry date is invalid, it 's should be like 2006-01-02",
	"Row %s: Used since date is invalid, it 's should be like 2006-01-02":      "Row %s: Used since date is invalid, it 's should be like 2006-01-02",
	"Row %s: depreciation period should be number":                             "Row %s: depreciation period should be number",
	"Row %s: asset is duplicated":                                              "Row %s: asset is duplicated",
	"Import asset successfully.":                                               "Import asset successfully.",
}

var JpAssetCategories = map[string]string{
	"Asset type code":                          "資産タイプコード",
	"Asset code":                               "コード",
	"Asset name":                               "資産名",
	"Employee Id":                              "社員コード",
	"User name":                                "使用者",
	"Managed by Id":                            "管理者ID",
	"Managed by name":                          "管理者",
	"Branch Id":                                "ブランチコード",
	"Branch":                                   "ブランチ",
	"Status":                                   "資産の現状",
	"Description":                              "説明",
	"Purchase price":                           "購入額",
	"Purchase date":                            "購入日",
	"Warranty expiry date":                     "保証日の終期",
	"Used since":                               "使用初日",
	"Depreciation end date":                    "償却始日",
	"Depreciation period":                      "償却期限",
	"Row %s: asset type can't not be blank":    "%s行目: 資産タイプコードが空白にすることはできません",
	"Row %s: asset type should be number":      "%s行目: 資産タイプコードが番号である必要があります",
	"Row %s: asset type code not exists":       "%s行目: 資産タイプコードが保存しません",
	"Row %s: asset code can't not be blank":    "%s行目: 資産コードが空白にすることはできません",
	"Row %s: employee id is not exist":         "%s行目: 社員コードが保存しません",
	"Row %s: Managed by Id can't not be blank": "%s行目: 管理者IDが空白にすることはできません",
	"Row %s: Manager employee id is not exist": "%s行目: 管理者IDが番号である必要があります",
	"Row %s: Branch Id can't not be blank":     "%s行目: ブランチコードが空白にすることはできません",
	"Row %s: Branch Id should be number":       "%s行目: ブランチコードが番号である必要があります",
	"Row %s: Branch Id not exists":             "%s行目: ブランチコードが保存しません",
	"Row %s: Status can't not be blank":        "%s行目: 資産の現状が空白にすることはできません",
	"Row %s: Status Id should be number":       "%s行目: 資産の現状が番号である必要があります",
	"Row %s: Status Id not exists":             "%s行目: 資産の現状IDが保存しません",
	"Row %s: Purchase price should be number":  "%s行目: 購入額が番号である必要があります",
	"Row %s: Purchase date is invalid, it 's should be like 2006-01-02":        "%s行目: 購入日が無効です,　2006-01-02のようになります",
	"Row %s: Warranty expiry date is invalid, it 's should be like 2006-01-02": "%s行目:　保証日の終期が無効です、2006-01-02のようになります",
	"Row %s: Used since date is invalid, it 's should be like 2006-01-02":      "%s行目: 使用初日が無効です、2006-01-02のようになります",
	"Row %s: depreciation period should be number":                             "%s行目: 償却始日が番号である必要があります",
	"Row %s: asset is duplicated":                                              "%s行目: 資産が重複だった",
	"Import asset successfully.":                                               "インポートすることが成功しました。",
}

var VnAssetCategories = map[string]string{
	"Asset type code":                          "Mã loại tài sản",
	"Asset code":                               "Mã tài sản",
	"Asset name":                               "Tên tài sản",
	"Employee Id":                              "Mã nhân viên",
	"User name":                                "Người sử dụng ",
	"Managed by Id":                            "Mã người quản lí ",
	"Managed by name":                          "Tên người quản lí",
	"Branch Id":                                "Mã chi nhánh",
	"Branch":                                   "Chi nhánh",
	"Status":                                   "Tình trạng mượn",
	"Description":                              "Mô tả",
	"Purchase price":                           "Giá mua",
	"Purchase date":                            "Ngày mua",
	"Warranty expiry date":                     "Ngày kết thúc bảo hành",
	"Used since":                               "Ngày bắt đầu sử dụng",
	"Depreciation end date":                    "Ngày kết thúc khấu hao",
	"Depreciation period":                      "Thời gian khấu hao",
	"Row %s: asset type can't not be blank":    "Dòng %s: Mã loại tài sản không được bỏ trống",
	"Row %s: asset type should be number":      "Dòng %s: Mã loại tài sản phải là số",
	"Row %s: asset type code not exists":       "Dòng %s: Mã loại tài sản không tồn tại",
	"Row %s: asset code can't not be blank":    "Dòng %s: Mã tài sản không được bỏ trống",
	"Row %s: employee id is not exist":         "Dòng %s: Mã nhân viên không tồn tại",
	"Row %s: Managed by Id can't not be blank": "Dòng %s: Mã người quản lý không được để trống",
	"Row %s: Manager employee id is not exist": "Dòng %s: Mã người quản lý không tồn tại",
	"Row %s: Branch Id can't not be blank":     "Dòng %s: Mã chi nhánh không được để rỗng",
	"Row %s: Branch Id should be number":       "Dòng %s: Mã chi nhánh phải là số",
	"Row %s: Branch Id not exists":             "Dòng %s: Mã chi nhánh không tồn tại",
	"Row %s: Status can't not be blank":        "Dòng %s: Trạng thái không để rỗng",
	"Row %s: Status Id should be number":       "Dòng %s: Trạng thái phải là số",
	"Row %s: Status Id not exists":             "Dòng %s: Trạng thái không tồn tại",
	"Row %s: Purchase price should be number":  "Dòng %s: Giá mua phải là số",
	"Row %s: Purchase date is invalid, it 's should be like 2006-01-02":        "Dòng %s: Ngày mua không hợp lệ, phải có định dạng 2006-01-02",
	"Row %s: Warranty expiry date is invalid, it 's should be like 2006-01-02": "Dòng %s: Ngày kết thúc bảo hành không hợp lệ, phải có định dạng 2006-01-02",
	"Row %s: Used since date is invalid, it 's should be like 2006-01-02":      "Dòng %s: Ngày sử dụng không hợp lệ, phải có định dạng 2006-01-02",
	"Row %s: depreciation period should be number":                             "Dòng %s: Ngày kết thúc khấu hao không hợp lệ, phải có định dạng 2006-01-02",
	"Row %s: asset is duplicated":                                              "Dòng %s: tài sản bị lặp lại",
	"Import asset successfully.":                                               "Import thành công.",
}
