name: Docker Image CI

on:
  push:
    branches: [ thanh_testgit ]
  pull_request:
    branches: [ thanh_testgit ]
jobs:

  deploy-stg:
    runs-on: windows-latest
    environment: staging
    container: google/cloud-sdk:alpine
    steps:
      - run: echo $SERVICE_ACCOUNT_STG > /tmp/gcloud-key.json
      - run: gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
      - run: gcloud config set project microerp-stg
      - run: cat .env.stg > .env
      - run: cd cmd/frontapi && gcloud app deploy --quiet app-stg.yaml
